require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
